default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: zhapp_development


test:
  <<: *default
  database: zhapp_test

production:
  <<: *default
  database: zhapp_production
  username: zhapp
  password: <%= ENV['ZHAPP_DATABASE_PASSWORD'] %>
